sudo: required
services: 
  - docker

before_install:
  - docker build -t palankarravi/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true palankarravi/react-test npm run test -- --coverage

after_success:
  - docker build -t palankarravi/multi-client ./client
  - docker build -t palankarravi/multi-nginx ./nginx
  - docker build -t palankarravi/multi-server ./server
  - docker build -t palankarravi/multi-worker ./worker
  #Login to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER-ID" --password-stdin
  #take those inages and push them to docker_container
  - docker push palankarravi/multi-client
  - docker push palankarravi/multi-nginx 
  - docker push palankarravi/multi-server
  - docker push palankarravi/multi-worker